import{a as E,S,i as c}from"./assets/vendor-mdVVRe9K.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="46174966-07e02f6c406b1cfe44f6656da",$="https://pixabay.com/api/";async function g(o,e=1){try{const r=await E.get($,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}});if(r.data.hits.length===0)throw new Error("No images found");return r.data}catch(r){throw console.error("Error fetching images:",r),r}}function f(o){const e=document.querySelector(".gallery"),r=o.map(({webformatURL:l,largeImageURL:t,tags:s,likes:a,views:w,comments:v,downloads:L})=>`
        <li class="gallery-item">
           <a href="${t}">
            <img src="${l}" alt="${s}" loading="lazy" class="preview-image"/>
          </a>
          <div class="info">
            <p><b>Likes:</b> ${a}</p>
            <p><b>Views:</b> ${w}</p>
            <p><b>Comments:</b> ${v}</p>
            <p><b>Downloads:</b> ${L}</p>
          </div>
        </li>
      `).join("");e.insertAdjacentHTML("beforeend",r)}const B=document.getElementById("search-form"),u=document.querySelector(".gallery"),n=document.getElementById("load-more"),i=document.querySelector(".loader");let d=1,y="",p=0;const h=new S(".gallery a");function m(o){c.error({message:"Something went wrong, please try again later.",position:"topRight",class:"custom-iziToast-error"})}function b(){const o=u.querySelector(".gallery-item");return o?o.getBoundingClientRect().height:0}B.addEventListener("submit",async o=>{o.preventDefault(),y=o.currentTarget.elements.query.value.trim(),u.innerHTML="",d=1,p=0,n.style.display="none",i.style.position="static",i.style.display="block";try{const e=await g(y,d);if(i.style.display="none",e.hits.length===0){c.error({message:"Sorry, no images found for your search query. Please try again!",position:"topRight",class:"custom-iziToast-error"});return}p=e.totalHits,f(e.hits),h.refresh();const r=b();window.scrollBy({top:r*2,behavior:"smooth"}),n.style.display=e.hits.length<15?"none":"block"}catch{i.style.display="none",m()}});n.addEventListener("click",async()=>{d+=1;const o=n.getBoundingClientRect();i.style.position="absolute",i.style.top=`${o.top+window.scrollY}px`,i.style.left=`${o.left+window.scrollX}px`,n.style.display="none",i.style.display="block";try{const e=await g(y,d);if(i.style.display="none",e.hits.length===0){c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"custom-iziToast-info"}),n.style.display="none";return}u.children.length+e.hits.length>=p?(n.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"custom-iziToast-info"})):n.style.display="block",f(e.hits),h.refresh();const r=b();window.scrollBy({top:r*2,behavior:"smooth"})}catch{i.style.display="none",m()}});
//# sourceMappingURL=index.js.map
